### ISSUE TITLE
Load codec libraries failed

### ISSUE THREAD

**Issue by drsasapavlovic** [Khang-NT/Listen-2-Youtube#72]
I have Huawei P8max rooted, 5.1.1. After opening the latest version and downloding and unzipping libraries, the app crashes and can't open anymore. The version of 15 MB is working, but only for audio files, video files can't open

**Comment by Khang-NT** [comment]
Please let me known what library my app downloaded?
arm64-v8a or armeabi-v7a or something else?

**Comment by Khang-NT** [comment]
Okey, I see that your device's cpu is arm 64bit.
Please download my latest build here:
https://drive.google.com/file/d/0B1-d3Xs9yeFHcWJHNTQ0ak0zWms/view?usp=sharing
If it still crashing, can you send me error log in folder:
`/data/data/com.kapp.youtube/files/`
The extension of error log files is `*.stacktrace`

**Comment by drsasapavlovic** [comment]
arm64-v8a
23.06.2016. 08:56 AM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by drsasapavlovic** [comment]
arm64-v8a

**Comment by drsasapavlovic** [comment]
Package: com.kapp.youtube
Version Code: 12
Version Name: 1.2.2 test
Android: 5.1.1
Android Build: DAV-701LV100R001C100B002
Manufacturer: HUAWEI
Model: HUAWEI P8max
Thread: main-1
CrashReporter Key: 580CCC84-D737-6869-AD38-3A1D5E1167FAA91E82DF
Start Date: Thu Jun 23 09:07:52 GMT+02:00 2016
Date: Thu Jun 23 09:08:05 GMT+02:00 2016

java.lang.UnsatisfiedLinkError: dlopen failed: library "libvlc.so" not found
at java.lang.Runtime.load(Runtime.java:343)
at java.lang.System.load(System.java:990)
at org.videolan.libvlc.LibVLC.loadLibraries(LibVLC.java:205)
at org.videolan.libvlc.LibVLC.<init>(LibVLC.java:51)
at
com.kapp.youtube.mediaplayer.MyMediaPlayer.getLibVLC(MyMediaPlayer.java:37)
at com.kapp.youtube.mediaplayer.MyMediaPlayer.<init>(MyMediaPlayer.java:48)
at
com.kapp.youtube.service.PlaybackService.onCreate(PlaybackService.java:117)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:2911)
at android.app.ActivityThread.access$2200(ActivityThread.java:163)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1479)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5601)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
23.06.2016. 09:05 AM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by drsasapavlovic** [comment]
Package: com.kapp.youtube
Version Code: 12
Version Name: 1.2.2 test
Android: 5.1.1
Android Build: DAV-701LV100R001C100B002
Manufacturer: HUAWEI
Model: HUAWEI P8max
Thread: main-1
CrashReporter Key: 580CCC84-D737-6869-AD38-3A1D5E1167FAA91E82DF
Start Date: Thu Jun 23 09:07:52 GMT+02:00 2016
Date: Thu Jun 23 09:08:05 GMT+02:00 2016

java.lang.UnsatisfiedLinkError: dlopen failed: library "libvlc.so" not found
	at java.lang.Runtime.load(Runtime.java:343)
	at java.lang.System.load(System.java:990)
	at org.videolan.libvlc.LibVLC.loadLibraries(LibVLC.java:205)
	at org.videolan.libvlc.LibVLC.<init>(LibVLC.java:51)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.getLibVLC(MyMediaPlayer.java:37)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.<init>(MyMediaPlayer.java:48)
	at com.kapp.youtube.service.PlaybackService.onCreate(PlaybackService.java:117)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2911)
	at android.app.ActivityThread.access$2200(ActivityThread.java:163)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1479)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5601)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

**Comment by Khang-NT** [comment]
Can you COPY libvlc.so
from folder: `com.kapp.youtube/files/libs`
to folder: `com.kapp.youtube/lib/arm64-v8a`

Then try to re-open the app again

**Comment by drsasapavlovic** [comment]
I am using root explorer and i cannot do that. I mean, i can copy: libvlc.so, but i cannot paste it to the another folder?

**Comment by Khang-NT** [comment]
okey, just go to `com.kapp.youtube/lib/arm64-v8a`
Then create new empty file with name: `libvlc.so`

**Comment by drsasapavlovic** [comment]
I can just put the text: libvlc.so to: com.kapp.youtube/lib. I cannot see arm64-v8a.

**Comment by drsasapavlovic** [comment]
Package: com.kapp.youtube
Version Code: 12
Version Name: 1.2.2
Android: 5.1.1
Android Build: DAV-701LV100R001C100B002
Manufacturer: HUAWEI
Model: HUAWEI P8max
Thread: main-1
CrashReporter Key: 580CCC84-D737-6869-AD38-3A1D5E1167FAA91E82DF
Start Date: Thu Jun 23 09:31:28 GMT+02:00 2016
Date: Thu Jun 23 09:31:42 GMT+02:00 2016

java.lang.UnsatisfiedLinkError: dlopen failed: library "libvlc.so" not found
	at java.lang.Runtime.load(Runtime.java:343)
	at java.lang.System.load(System.java:990)
	at org.videolan.libvlc.LibVLC.loadLibraries(LibVLC.java:205)
	at org.videolan.libvlc.LibVLC.<init>(LibVLC.java:51)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.getLibVLC(MyMediaPlayer.java:37)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.<init>(MyMediaPlayer.java:48)
	at com.kapp.youtube.service.PlaybackService.onCreate(PlaybackService.java:117)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2911)
	at android.app.ActivityThread.access$2200(ActivityThread.java:163)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1479)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5601)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

**Comment by Khang-NT** [comment]
Oh, sorry. Copy to `com.kapp.youtube/lib` is right. But It still crashing?
Hmm. I thought Root explorer can copy file?
Can you help me, try COPY libvlc.so
from folder: `com.kapp.youtube/files/libs`
to folder: `com.kapp.youtube/lib`

**Comment by drsasapavlovic** [comment]
I can just put the text: libvlc.so to: com.kapp.youtube/lib. I cannot see arm64-v8a.

**Comment by drsasapavlovic** [comment]
I cannot do that neither.

**Comment by drsasapavlovic** [comment]
lib is not folder.

**Comment by Khang-NT** [comment]
hey guy. I have new build to fix it.
Please uninstall current version first!!!
And install new one:
https://drive.google.com/file/d/0B1-d3Xs9yeFHVHEwWHUxbXBfcTA/view?usp=sharing

**Comment by drsasapavlovic** [comment]
The same situation:

Package: com.kapp.youtube
Version Code: 12
Version Name: 1.2.2 test2
Android: 5.1.1
Android Build: DAV-701LV100R001C100B002
Manufacturer: HUAWEI
Model: HUAWEI P8max
Thread: main-1
CrashReporter Key: 580CCC84-D737-6869-AD38-3A1D5E1167FAA91E82DF
Start Date: Thu Jun 23 12:30:38 GMT+02:00 2016
Date: Thu Jun 23 12:31:15 GMT+02:00 2016

java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.kapp.youtube-1/lib/arm64/libvlc.so" is too small to be an ELF executable: only found 0 bytes
	at java.lang.Runtime.loadLibrary(Runtime.java:383)
	at java.lang.System.loadLibrary(System.java:997)
	at org.videolan.libvlc.LibVLC.loadLibraries(LibVLC.java:209)
	at org.videolan.libvlc.LibVLC.<init>(LibVLC.java:51)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.getLibVLC(MyMediaPlayer.java:37)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.<init>(MyMediaPlayer.java:48)
	at com.kapp.youtube.service.PlaybackService.onCreate(PlaybackService.java:117)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2911)
	at android.app.ActivityThread.access$2200(ActivityThread.java:163)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1479)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5601)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

**Comment by Khang-NT** [comment]
How about this one:
https://drive.google.com/file/d/0B1-d3Xs9yeFHVHEwWHUxbXBfcTA/view?usp=sharing

**Uninstall or clear data current verion first!!**

**Comment by drsasapavlovic** [comment]
Nothing:

Package: com.kapp.youtube
Version Code: 12
Version Name: 1.2.2 test2
Android: 5.1.1
Android Build: DAV-701LV100R001C100B002
Manufacturer: HUAWEI
Model: HUAWEI P8max
Thread: main-1
CrashReporter Key: 580CCC84-D737-6869-AD38-3A1D5E1167FAA91E82DF
Start Date: Thu Jun 23 12:56:18 GMT+02:00 2016
Date: Thu Jun 23 12:56:39 GMT+02:00 2016

java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.kapp.youtube-1/lib/arm64/libvlc.so" is too small to be an ELF executable: only found 0 bytes
	at java.lang.Runtime.loadLibrary(Runtime.java:383)
	at java.lang.System.loadLibrary(System.java:997)
	at org.videolan.libvlc.LibVLC.loadLibraries(LibVLC.java:209)
	at org.videolan.libvlc.LibVLC.<init>(LibVLC.java:51)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.getLibVLC(MyMediaPlayer.java:37)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.<init>(MyMediaPlayer.java:48)
	at com.kapp.youtube.service.PlaybackService.onCreate(PlaybackService.java:117)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2911)
	at android.app.ActivityThread.access$2200(ActivityThread.java:163)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1479)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5601)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

**Comment by Khang-NT** [comment]
Can you download
https://youtube-app-d1576.firebaseapp.com/api/v1/arm64-v8a/libs.zip
Then unzip to folder:
/data/app/com.kapp.youtube-1/lib/arm64/

**Comment by Khang-NT** [comment]
Please try with new version (no need to uninstall old one)
https://drive.google.com/file/d/0B1-d3Xs9yeFHbUkzdTRIU3gxOTQ/view?usp=sharing

**Comment by drsasapavlovic** [comment]
Nothing again.
Unzipping libs to arm64, was successful, app is not crashing, but the downloaded video i cannot reproduce, only the music.

Package: com.kapp.youtube
Version Code: 12
Version Name: 1.2.2 test2
Android: 5.1.1
Android Build: DAV-701LV100R001C100B002
Manufacturer: HUAWEI
Model: HUAWEI P8max
Thread: main-1
CrashReporter Key: 580CCC84-D737-6869-AD38-3A1D5E1167FAA91E82DF
Start Date: Thu Jun 23 13:29:21 GMT+02:00 2016
Date: Thu Jun 23 13:30:59 GMT+02:00 2016

java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.kapp.youtube-1/lib/arm64/libvlc.so" is too small to be an ELF executable: only found 0 bytes
	at java.lang.Runtime.loadLibrary(Runtime.java:383)
	at java.lang.System.loadLibrary(System.java:997)
	at org.videolan.libvlc.LibVLC.loadLibraries(LibVLC.java:209)
	at org.videolan.libvlc.LibVLC.<init>(LibVLC.java:51)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.getLibVLC(MyMediaPlayer.java:37)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.<init>(MyMediaPlayer.java:48)
	at com.kapp.youtube.service.PlaybackService.onCreate(PlaybackService.java:117)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2911)
	at android.app.ActivityThread.access$2200(ActivityThread.java:163)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1479)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5601)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

**Comment by Khang-NT** [comment]
This is lasted build:
https://drive.google.com/a/hcmut.edu.vn/file/d/0B1-d3Xs9yeFHRkxOck5wSW1fMlE/view?usp=sharing

I sure it wont crash.
Remember uninstall old one!

You can't download video or can't open video?

**Comment by drsasapavlovic** [comment]
Can't open video
23.06.2016. 01:40 PM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by Khang-NT** [comment]
My app doesn't support open video, it just play sound of video.
Does it crash when open video?

**Comment by drsasapavlovic** [comment]
New app crashes to. Previous don't crach when i listen the downloaded video
musiv.
23.06.2016. 01:50 PM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by drsasapavlovic** [comment]
Package: com.kapp.youtube
Version Code: 12
Version Name: 1.2.2 test2
Android: 5.1.1
Android Build: DAV-701LV100R001C100B002
Manufacturer: HUAWEI
Model: HUAWEI P8max
Thread: main-1
CrashReporter Key: 580CCC84-D737-6869-AD38-3A1D5E1167FAA91E82DF
Start Date: Thu Jun 23 13:50:18 GMT+02:00 2016
Date: Thu Jun 23 13:50:36 GMT+02:00 2016

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.kapp.youtube-1/base.apk"],nativeLibraryDirectories=[/data/app/com.kapp.youtube-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libvlc.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:378)
	at java.lang.System.loadLibrary(System.java:997)
	at org.videolan.libvlc.LibVLC.loadLibraries(LibVLC.java:209)
	at org.videolan.libvlc.LibVLC.<init>(LibVLC.java:51)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.getLibVLC(MyMediaPlayer.java:37)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.<init>(MyMediaPlayer.java:48)
	at com.kapp.youtube.service.PlaybackService.onCreate(PlaybackService.java:117)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2911)
	at android.app.ActivityThread.access$2200(ActivityThread.java:163)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1479)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5601)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

**Comment by Khang-NT** [comment]
Oh, my mistake.
Please unzip my library to folder: /system/lib64

**Comment by drsasapavlovic** [comment]
It's ok now using your last advice.
Thanks a lot.

**Comment by Khang-NT** [comment]
okey. So it's latest build, you help me a lot to complete it.
https://drive.google.com/file/d/0B1-d3Xs9yeFHT2pKeWNrdWpJX1U/view?usp=sharing

**Comment by drsasapavlovic** [comment]
It crashes again.

Package: com.kapp.youtube
Version Code: 13
Version Name: 1.2.3
Android: 5.1.1
Android Build: DAV-701LV100R001C100B002
Manufacturer: HUAWEI
Model: HUAWEI P8max
Thread: main-1
CrashReporter Key: 580CCC84-D737-6869-AD38-3A1D5E1167FAA91E82DF
Start Date: Thu Jun 23 15:58:44 GMT+02:00 2016
Date: Thu Jun 23 15:59:07 GMT+02:00 2016

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.kapp.youtube-1/base.apk"],nativeLibraryDirectories=[/data/app/com.kapp.youtube-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libvlc.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:378)
	at java.lang.System.loadLibrary(System.java:997)
	at org.videolan.libvlc.LibVLC.loadLibraries(LibVLC.java:209)
	at org.videolan.libvlc.LibVLC.<init>(LibVLC.java:51)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.getLibVLC(MyMediaPlayer.java:37)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.<init>(MyMediaPlayer.java:48)
	at com.kapp.youtube.service.PlaybackService.onCreate(PlaybackService.java:117)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2911)
	at android.app.ActivityThread.access$2200(ActivityThread.java:163)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1479)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5601)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

**Comment by Khang-NT** [comment]
Does /system/lib64/libvlc.so file exist?

**Comment by drsasapavlovic** [comment]
No
23.06.2016. 04:05 PM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:

**Comment by Khang-NT** [comment]
oh, may be I sent you wrong link.
Please uninstall old one, and try this:
https://drive.google.com/open?id=0B1-d3Xs9yeFHbUkzdTRIU3gxOTQ

**Comment by drsasapavlovic** [comment]
Bad.

Package: com.kapp.youtube
Version Code: 12
Version Name: 1.2.3
Android: 5.1.1
Android Build: DAV-701LV100R001C100B002
Manufacturer: HUAWEI
Model: HUAWEI P8max
Thread: main-1
CrashReporter Key: 580CCC84-D737-6869-AD38-3A1D5E1167FAA91E82DF
Start Date: Thu Jun 23 16:22:47 GMT+02:00 2016
Date: Thu Jun 23 16:23:07 GMT+02:00 2016

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.kapp.youtube-1/base.apk"],nativeLibraryDirectories=[/data/app/com.kapp.youtube-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libvlc.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:378)
	at java.lang.System.loadLibrary(System.java:997)
	at org.videolan.libvlc.LibVLC.loadLibraries(LibVLC.java:207)
	at org.videolan.libvlc.LibVLC.<init>(LibVLC.java:51)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.getLibVLC(MyMediaPlayer.java:37)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.<init>(MyMediaPlayer.java:48)
	at com.kapp.youtube.service.PlaybackService.onCreate(PlaybackService.java:117)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2911)
	at android.app.ActivityThread.access$2200(ActivityThread.java:163)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1479)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5601)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

**Comment by Khang-NT** [comment]
@@ So embarrassing with native libs 
Please help me test:
https://drive.google.com/open?id=0B1-d3Xs9yeFHbUkzdTRIU3gxOTQ

**Comment by drsasapavlovic** [comment]
Crash.

Package: com.kapp.youtube
Version Code: 12
Version Name: 1.2.3
Android: 5.1.1
Android Build: DAV-701LV100R001C100B002
Manufacturer: HUAWEI
Model: HUAWEI P8max
Thread: main-1
CrashReporter Key: 580CCC84-D737-6869-AD38-3A1D5E1167FAA91E82DF
Start Date: Thu Jun 23 17:53:52 GMT+02:00 2016
Date: Thu Jun 23 17:54:50 GMT+02:00 2016

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.kapp.youtube-1/base.apk"],nativeLibraryDirectories=[/data/app/com.kapp.youtube-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libvlc.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:378)
	at java.lang.System.loadLibrary(System.java:997)
	at org.videolan.libvlc.LibVLC.loadLibraries(LibVLC.java:207)
	at org.videolan.libvlc.LibVLC.<init>(LibVLC.java:51)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.getLibVLC(MyMediaPlayer.java:37)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.<init>(MyMediaPlayer.java:48)
	at com.kapp.youtube.service.PlaybackService.onCreate(PlaybackService.java:117)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2911)
	at android.app.ActivityThread.access$2200(ActivityThread.java:163)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1479)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5601)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

**Comment by Khang-NT** [comment]
And this:
https://drive.google.com/open?id=0B1-d3Xs9yeFHbUkzdTRIU3gxOTQ

**Comment by drsasapavlovic** [comment]
Finally, the good one!
