### ISSUE TITLE
Feedback 'Force Close'

### ISSUE THREAD

**Issue by Khang-NT** [Khang-NT/Listen-2-Youtube#90]
### Message from Ali sent on 2016-06-23 23:40:38 UTC###

> Hi. after the last 2 update this app doesn't work anymore , now after getting root access & download libs files keep get FC.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/344882/feedback/573507](https://rink.hockeyapp.net/manage/apps/344882/feedback/573507)

**Comment by drsasapavlovic** [comment]
After the last online update, it crashes again. The previous version is ok.

Package: com.kapp.youtube
Version Code: 14
Version Name: 1.2.3a
Android: 5.1.1
Android Build: DAV-701LV100R001C100B002
Manufacturer: HUAWEI
Model: HUAWEI P8max, Cpu: arm64-v8a
Thread: main-1
CrashReporter Key: 580CCC84-D737-6869-AD38-3A1D5E1167FAA91E82DF
Start Date: Fri Jun 24 01:46:08 GMT+02:00 2016
Date: Fri Jun 24 01:46:08 GMT+02:00 2016

java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.kapp.youtube-2/lib/arm64/libvlc.so" is too small to be an ELF executable: only found 0 bytes
	at java.lang.Runtime.loadLibrary(Runtime.java:383)
	at java.lang.System.loadLibrary(System.java:997)
	at org.videolan.libvlc.LibVLC.loadLibraries(LibVLC.java:207)
	at org.videolan.libvlc.LibVLC.<init>(LibVLC.java:51)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.getLibVLC(MyMediaPlayer.java:37)
	at com.kapp.youtube.mediaplayer.MyMediaPlayer.<init>(MyMediaPlayer.java:48)
	at com.kapp.youtube.service.PlaybackService.onCreate(PlaybackService.java:118)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2911)
	at android.app.ActivityThread.access$2200(ActivityThread.java:163)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1479)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5601)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

**Comment by Khang-NT** [comment]
oh, have you uninstall old one?

**Comment by drsasapavlovic** [comment]
Yes. I reinstalled the app from xda lab and it's working.
24.06.2016. 04:28 AM, "Nguyễn Triết Khang" <notifications@github.com> je
napisao/la:
